name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
    
      - name: 安装 python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 安装依赖
        run: |
          pip install playwright pytest pytest-html
          
      - name: 安装 Chromium 以及系统依赖
        run: |
          playwright install chromium --with-deps
      
      - name: 安装并且启动 httpbin
        run: |
          pip install httpbin gunicorn
          gunicorn httpbin:app -b 127.0.0.1:8080 --daemon
          sleep 2
          curl http://127.0.0.1:8080/get # 确认启动成功

      - name: 运行测试
        run: |
          pytest test_httpbin_ci.py-v --html --self-contained-html

      - name: 上传报告
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: report.html
        
